// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[Table("AnswerTF")]
public partial class AnswerTf
{
    [Key]
    public int QuestionId { get; set; }

    public bool IsTrue { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("AnswerTf")]
    public virtual Question Question { get; set; }
}