// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

public partial class Branch
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(6)]
    [Unicode(false)]
    public string ZipCode { get; set; }

    [Required]
    [StringLength(5)]
    public string StreetNo { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<BranchDept> BranchDepts { get; set; } = new List<BranchDept>();

    [InverseProperty("Branch")]
    public virtual ICollection<Pool> Pools { get; set; } = new List<Pool>();

    [InverseProperty("Branch")]
    public virtual ICollection<StaffBranchDepartmentManagement> StaffBranchDepartmentManagements { get; set; } = new List<StaffBranchDepartmentManagement>();

    [InverseProperty("Branch")]
    public virtual ICollection<StaffBranchIntakeDepartmentCourseTeach> StaffBranchIntakeDepartmentCourseTeaches { get; set; } = new List<StaffBranchIntakeDepartmentCourseTeach>();

    [InverseProperty("Branch")]
    public virtual ICollection<StaffBranchIntakeWorksFor> StaffBranchIntakeWorksFors { get; set; } = new List<StaffBranchIntakeWorksFor>();

    [InverseProperty("Branch")]
    public virtual StaffBranchManage StaffBranchManage { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<StudentIntakeBranchDepartmentStudy> StudentIntakeBranchDepartmentStudies { get; set; } = new List<StudentIntakeBranchDepartmentStudy>();

    [ForeignKey("ZipCode")]
    [InverseProperty("Branch")]
    public virtual Location ZipCodeNavigation { get; set; }
}