// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("Index", "QuestionId")]
public partial class Choice
{
    [Key]
    [Column("Index_")]
    public int Index { get; set; }

    [Key]
    public int QuestionId { get; set; }

    [Column("content")]
    [StringLength(255)]
    public string Content { get; set; }

    public bool IsCorrect { get; set; }

    [InverseProperty("Choice")]
    public virtual ICollection<MultiChoiceResponse> MultiChoiceResponses { get; set; } = new List<MultiChoiceResponse>();

    [ForeignKey("QuestionId")]
    [InverseProperty("Choices")]
    public virtual Question Question { get; set; }
}