// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[Index("Disc", Name = "UQ_Dept_Disc", IsUnique = true)]
[Index("Name", Name = "UQ_Dept_Name", IsUnique = true)]
public partial class Department
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(10)]
    public string Name { get; set; }

    [Required]
    [StringLength(30)]
    public string Disc { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<BranchDept> BranchDepts { get; set; } = new List<BranchDept>();

    [InverseProperty("Dept")]
    public virtual ICollection<IntakeDeptCourse> IntakeDeptCourses { get; set; } = new List<IntakeDeptCourse>();

    [InverseProperty("Dept")]
    public virtual ICollection<Pool> Pools { get; set; } = new List<Pool>();

    [InverseProperty("Department")]
    public virtual ICollection<StaffBranchDepartmentManagement> StaffBranchDepartmentManagements { get; set; } = new List<StaffBranchDepartmentManagement>();

    [InverseProperty("Department")]
    public virtual ICollection<StaffBranchDepartmentWorksFor> StaffBranchDepartmentWorksFors { get; set; } = new List<StaffBranchDepartmentWorksFor>();

    [InverseProperty("Department")]
    public virtual ICollection<StaffBranchIntakeDepartmentCourseTeach> StaffBranchIntakeDepartmentCourseTeaches { get; set; } = new List<StaffBranchIntakeDepartmentCourseTeach>();

    [InverseProperty("Department")]
    public virtual ICollection<StudentIntakeBranchDepartmentStudy> StudentIntakeBranchDepartmentStudies { get; set; } = new List<StudentIntakeBranchDepartmentStudy>();
}