// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

public partial class ExamModel
{
    [Key]
    public int Id { get; set; }

    public int? PoolId { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<MultiChoiceResponse> MultiChoiceResponses { get; set; } = new List<MultiChoiceResponse>();

    [ForeignKey("PoolId")]
    [InverseProperty("ExamModels")]
    public virtual Pool Pool { get; set; }

    [InverseProperty("ExamModel")]
    public virtual ICollection<StudentExamModel> StudentExamModels { get; set; } = new List<StudentExamModel>();

    [InverseProperty("Exam")]
    public virtual ICollection<TrueFalseResponse> TrueFalseResponses { get; set; } = new List<TrueFalseResponse>();

    [ForeignKey("ExamModelId")]
    [InverseProperty("ExamModels")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}