// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class GetActivePoolResult
    {
        public int Id { get; set; }
        public byte IsActive { get; set; }
        public long StaffId { get; set; }
        public int DeptId { get; set; }
        public int BranchId { get; set; }
        public int CourseId { get; set; }
        [StringLength(255)]
        public string Title { get; set; }
        public int IntakeId { get; set; }
        public int NoOfMedium { get; set; }
        public int NoOfEasy { get; set; }
        public int NoOfDifficult { get; set; }
    }
}
