// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class GetBranchByIdResult
    {
        public int Id { get; set; }
        [StringLength(6)]
        public string ZipCode { get; set; }
        [StringLength(5)]
        public string StreetNo { get; set; }
        public bool IsDeleted { get; set; }
    }
}
