// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class GetPoolQuestionsResult
    {
        public int Id { get; set; }
        public byte Type { get; set; }
        public byte Level { get; set; }
        public int TopicId { get; set; }
        [StringLength(255)]
        public string Content { get; set; }
        public DateOnly createdDate { get; set; }
        [StringLength(2147483647)]
        public string Choices { get; set; }
        [StringLength(2147483647)]
        public string Images { get; set; }
    }
}
