// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class IntakeDeptCoursesGetResult
    {
        public int DeptId { get; set; }
        public int CourseId { get; set; }
        public int IntakeId { get; set; }
    }
}
