// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("DeptId", "CourseId", "IntakeId")]
public partial class IntakeDeptCourse
{
    [Key]
    public int DeptId { get; set; }

    [Key]
    public int CourseId { get; set; }

    [Key]
    public int IntakeId { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("IntakeDeptCourses")]
    public virtual Course Course { get; set; }

    [ForeignKey("DeptId")]
    [InverseProperty("IntakeDeptCourses")]
    public virtual Department Dept { get; set; }

    [ForeignKey("IntakeId")]
    [InverseProperty("IntakeDeptCourses")]
    public virtual Intake Intake { get; set; }

    [InverseProperty("IntakeDeptCourse")]
    public virtual ICollection<StaffBranchIntakeDepartmentCourseTeach> StaffBranchIntakeDepartmentCourseTeaches { get; set; } = new List<StaffBranchIntakeDepartmentCourseTeach>();
}