// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class LocationsGetResult
    {
        [StringLength(6)]
        public string ZipCode { get; set; }
        [StringLength(50)]
        public string Governate { get; set; }
    }
}
