// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

public partial class Location
{
    [Key]
    [StringLength(6)]
    [Unicode(false)]
    public string ZipCode { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Governate { get; set; }

    [InverseProperty("ZipCodeNavigation")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("ZipCodeNavigation")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}