// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("PoolId", "QuestionId")]
[Table("PoolQuestion")]
public partial class PoolQuestion
{
    [Key]
    public int PoolId { get; set; }

    [Key]
    public int QuestionId { get; set; }

    public byte? IsIncluded { get; set; }

    [ForeignKey("PoolId")]
    [InverseProperty("PoolQuestions")]
    public virtual Pool Pool { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("PoolQuestions")]
    public virtual Question Question { get; set; }
}