// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

public partial class Pool
{
    [Key]
    public int Id { get; set; }

    public byte IsActive { get; set; }

    public long StaffId { get; set; }

    public int DeptId { get; set; }

    public int BranchId { get; set; }

    public int CourseId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    public int IntakeId { get; set; }

    public int NoOfMedium { get; set; }

    public int NoOfEasy { get; set; }

    public int NoOfDifficult { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Pools")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Pool")]
    public virtual Configuration Configuration { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Pools")]
    public virtual Course Course { get; set; }

    [ForeignKey("DeptId")]
    [InverseProperty("Pools")]
    public virtual Department Dept { get; set; }

    [InverseProperty("Pool")]
    public virtual ICollection<ExamModel> ExamModels { get; set; } = new List<ExamModel>();

    [ForeignKey("IntakeId")]
    [InverseProperty("Pools")]
    public virtual Intake Intake { get; set; }

    [InverseProperty("Pool")]
    public virtual ICollection<PoolQuestion> PoolQuestions { get; set; } = new List<PoolQuestion>();

    [ForeignKey("StaffId")]
    [InverseProperty("Pools")]
    public virtual Staff Staff { get; set; }
}