// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class ProcessedPoolsResult
    {
        public int PId { get; set; }
        public byte PIsActive { get; set; }
        public long PStaffId { get; set; }
        public int PDeptId { get; set; }
        public int PBranchId { get; set; }
        public int PCourseId { get; set; }
        [StringLength(255)]
        public string PTitle { get; set; }
        public int PIntakeId { get; set; }
        public int PNoOfMedium { get; set; }
        public int PNoOfEasy { get; set; }
        public int PNoOfDifficult { get; set; }
        public byte CNoOfDifficult { get; set; }
        public byte CNoOfMedium { get; set; }
        public byte CNoOfEasy { get; set; }
        public byte CGradeForDifficult { get; set; }
        public byte CGradeForMedium { get; set; }
        public byte CGradeForEasy { get; set; }
        public DateOnly? CDate { get; set; }
        public TimeOnly? CStartingTime { get; set; }
        public TimeOnly? CEndingTime { get; set; }
        public int? CDuration { get; set; }
        public byte CNoOfModels { get; set; }
        public bool CCanModify { get; set; }
        [StringLength(10)]
        public string DName { get; set; }
        [StringLength(30)]
        public string CName { get; set; }
        [StringLength(6)]
        public string LZipCode { get; set; }
        [StringLength(50)]
        public string LGovernate { get; set; }
    }
}
