// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

public partial class ProfileImage
{
    [Key]
    [StringLength(30)]
    [Unicode(false)]
    public string ImageId { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string ImageUrl { get; set; }

    [InverseProperty("Image")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}