// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

public partial class Question
{
    [Key]
    public int Id { get; set; }

    public byte Type { get; set; }

    public byte Level { get; set; }

    public int TopicId { get; set; }

    public long? StaffId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Content { get; set; }

    public DateOnly CreatedDate { get; set; }

    public byte IsDeleted { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    [InverseProperty("Question")]
    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    [InverseProperty("Question")]
    public virtual ICollection<MultiChoiceResponse> MultiChoiceResponses { get; set; } = new List<MultiChoiceResponse>();

    [InverseProperty("Question")]
    public virtual ICollection<PoolQuestion> PoolQuestions { get; set; } = new List<PoolQuestion>();

    [ForeignKey("StaffId")]
    [InverseProperty("Questions")]
    public virtual Staff Staff { get; set; }

    [ForeignKey("TopicId")]
    [InverseProperty("Questions")]
    public virtual Topic Topic { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<TrueFalseResponse> TrueFalseResponses { get; set; } = new List<TrueFalseResponse>();

    [ForeignKey("QuestionId")]
    [InverseProperty("Questions")]
    public virtual ICollection<ExamModel> ExamModels { get; set; } = new List<ExamModel>();
}