// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("BranchId", "DepartmentId", "IntakeId")]
[Table("StaffBranchDepartmentManagement")]
[Index("StaffSsn", Name = "UQ_StaffSSN", IsUnique = true)]
public partial class StaffBranchDepartmentManagement
{
    [Column("StaffSSN")]
    public long StaffSsn { get; set; }

    [Key]
    public int BranchId { get; set; }

    [Key]
    public int DepartmentId { get; set; }

    public DateOnly? HiringDate { get; set; }

    [Key]
    public int IntakeId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("StaffBranchDepartmentManagements")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("BranchId, DepartmentId, IntakeId")]
    [InverseProperty("StaffBranchDepartmentManagement")]
    public virtual BranchDept BranchDept { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("StaffBranchDepartmentManagements")]
    public virtual Department Department { get; set; }

    [ForeignKey("IntakeId")]
    [InverseProperty("StaffBranchDepartmentManagements")]
    public virtual Intake Intake { get; set; }

    [ForeignKey("StaffSsn")]
    [InverseProperty("StaffBranchDepartmentManagement")]
    public virtual Staff StaffSsnNavigation { get; set; }
}