// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[Table("StaffBranchManage")]
[Index("BranchId", Name = "UQ_StaffBranchManage_Branch", IsUnique = true)]
public partial class StaffBranchManage
{
    [Key]
    [Column("StaffSSN")]
    public long StaffSsn { get; set; }

    public int BranchId { get; set; }

    public DateOnly? HiringDate { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("StaffBranchManage")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("StaffSsn")]
    [InverseProperty("StaffBranchManage")]
    public virtual Staff StaffSsnNavigation { get; set; }
}