// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class StaffBranchIntakeDeptCourseTeachGetResult
    {
        public long StaffSSN { get; set; }
        public int BranchId { get; set; }
        public int DepartmentId { get; set; }
        public int CourseId { get; set; }
        public int IntakeId { get; set; }
        public DateTime StartingDate { get; set; }
        public DateTime? EndingDate { get; set; }
    }
}
