// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("StaffSsn", "BranchId", "IntakeId")]
[Table("StaffBranchIntakeWorksFor")]
[Index("StaffSsn", "IntakeId", Name = "UQ_StaffSSN_IntakeId", IsUnique = true)]
public partial class StaffBranchIntakeWorksFor
{
    [Key]
    [Column("StaffSSN")]
    public long StaffSsn { get; set; }

    [Key]
    public int BranchId { get; set; }

    public DateOnly? HiringDate { get; set; }

    [Key]
    public int IntakeId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("StaffBranchIntakeWorksFors")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("IntakeId")]
    [InverseProperty("StaffBranchIntakeWorksFors")]
    public virtual Intake Intake { get; set; }

    [ForeignKey("StaffSsn")]
    [InverseProperty("StaffBranchIntakeWorksFors")]
    public virtual Staff StaffSsnNavigation { get; set; }
}