// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

public partial class Staff
{
    [Key]
    [Column("SSN")]
    public long Ssn { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Salary { get; set; }

    [InverseProperty("Staff")]
    public virtual ICollection<Pool> Pools { get; set; } = new List<Pool>();

    [InverseProperty("Staff")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [ForeignKey("Ssn")]
    [InverseProperty("Staff")]
    public virtual User SsnNavigation { get; set; }

    [InverseProperty("StaffSsnNavigation")]
    public virtual StaffBranchDepartmentManagement StaffBranchDepartmentManagement { get; set; }

    [InverseProperty("StaffSsnNavigation")]
    public virtual ICollection<StaffBranchDepartmentWorksFor> StaffBranchDepartmentWorksFors { get; set; } = new List<StaffBranchDepartmentWorksFor>();

    [InverseProperty("StaffSsnNavigation")]
    public virtual ICollection<StaffBranchIntakeDepartmentCourseTeach> StaffBranchIntakeDepartmentCourseTeaches { get; set; } = new List<StaffBranchIntakeDepartmentCourseTeach>();

    [InverseProperty("StaffSsnNavigation")]
    public virtual StaffBranchManage StaffBranchManage { get; set; }

    [ForeignKey("StaffSsn")]
    [InverseProperty("StaffSsns")]
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}