// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("StaffSsn", "BranchId", "DepartmentId", "IntakeId")]
[Table("StaffBranchDepartmentWorksFor")]
public partial class StaffBranchDepartmentWorksFor
{
    [Key]
    [Column("StaffSSN")]
    public long StaffSsn { get; set; }

    [Key]
    public int BranchId { get; set; }

    [Key]
    public int DepartmentId { get; set; }

    public DateOnly? HiringDate { get; set; }

    [Key]
    public int IntakeId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("StaffBranchDepartmentWorksFors")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("BranchId, DepartmentId, IntakeId")]
    [InverseProperty("StaffBranchDepartmentWorksFors")]
    public virtual BranchDept BranchDept { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("StaffBranchDepartmentWorksFors")]
    public virtual Department Department { get; set; }

    [ForeignKey("IntakeId")]
    [InverseProperty("StaffBranchDepartmentWorksFors")]
    public virtual Intake Intake { get; set; }

    [ForeignKey("StaffSsn")]
    [InverseProperty("StaffBranchDepartmentWorksFors")]
    public virtual Staff StaffSsnNavigation { get; set; }
}