// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("StaffSsn", "BranchId", "DepartmentId", "CourseId", "IntakeId")]
[Table("StaffBranchIntakeDepartmentCourseTeach")]
public partial class StaffBranchIntakeDepartmentCourseTeach
{
    [Key]
    [Column("StaffSSN")]
    public long StaffSsn { get; set; }

    [Key]
    public int BranchId { get; set; }

    [Key]
    public int DepartmentId { get; set; }

    [Key]
    public int CourseId { get; set; }

    [Key]
    public int IntakeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartingDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndingDate { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("StaffBranchIntakeDepartmentCourseTeaches")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("BranchId, DepartmentId, IntakeId")]
    [InverseProperty("StaffBranchIntakeDepartmentCourseTeaches")]
    public virtual BranchDept BranchDept { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("StaffBranchIntakeDepartmentCourseTeaches")]
    public virtual Course Course { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("StaffBranchIntakeDepartmentCourseTeaches")]
    public virtual Department Department { get; set; }

    [ForeignKey("IntakeId")]
    [InverseProperty("StaffBranchIntakeDepartmentCourseTeaches")]
    public virtual Intake Intake { get; set; }

    [ForeignKey("DepartmentId, CourseId, IntakeId")]
    [InverseProperty("StaffBranchIntakeDepartmentCourseTeaches")]
    public virtual IntakeDeptCourse IntakeDeptCourse { get; set; }

    [ForeignKey("StaffSsn")]
    [InverseProperty("StaffBranchIntakeDepartmentCourseTeaches")]
    public virtual Staff StaffSsnNavigation { get; set; }
}