// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("StudentId", "ExamModelId")]
[Table("StudentExamModel")]
public partial class StudentExamModel
{
    [Key]
    public long StudentId { get; set; }

    [Key]
    public int ExamModelId { get; set; }

    public bool? Attendance { get; set; }

    [Column("total")]
    public int? Total { get; set; }

    [ForeignKey("ExamModelId")]
    [InverseProperty("StudentExamModels")]
    public virtual ExamModel ExamModel { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("StudentExamModels")]
    public virtual Student Student { get; set; }
}