// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class StudentGetAllResult
    {
        public long SSN { get; set; }
        [StringLength(50)]
        public string Fname { get; set; }
        [StringLength(50)]
        public string Lname { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(6)]
        public string ZipCode { get; set; }
        [StringLength(5)]
        public string StreetNo { get; set; }
        public DateOnly BD { get; set; }
        public string Gender { get; set; }
        [StringLength(500)]
        public string ImageUrl { get; set; }
        [StringLength(11)]
        public string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
        [StringLength(100)]
        public string Faculty { get; set; }
        public int Grad_Year { get; set; }
        [Column("GPA", TypeName = "decimal(4,3)")]
        public decimal GPA { get; set; }
    }
}
