// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[PrimaryKey("StudentSsn", "IntakeId")]
[Table("StudentIntakeBranchDepartmentStudy")]
public partial class StudentIntakeBranchDepartmentStudy
{
    [Key]
    [Column("StudentSSN")]
    public long StudentSsn { get; set; }

    public int BranchId { get; set; }

    public int DepartmentId { get; set; }

    [Key]
    public int IntakeId { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("StudentIntakeBranchDepartmentStudies")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("BranchId, DepartmentId, IntakeId")]
    [InverseProperty("StudentIntakeBranchDepartmentStudies")]
    public virtual BranchDept BranchDept { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("StudentIntakeBranchDepartmentStudies")]
    public virtual Department Department { get; set; }

    [ForeignKey("IntakeId")]
    [InverseProperty("StudentIntakeBranchDepartmentStudies")]
    public virtual Intake Intake { get; set; }

    [ForeignKey("StudentSsn")]
    [InverseProperty("StudentIntakeBranchDepartmentStudies")]
    public virtual Student StudentSsnNavigation { get; set; }
}