// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

public partial class Student
{
    [Key]
    [Column("SSN")]
    public long Ssn { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Faculty { get; set; }

    [Column("Grad_Year")]
    public int GradYear { get; set; }

    [Column("GPA", TypeName = "decimal(4, 3)")]
    public decimal Gpa { get; set; }

    [InverseProperty("StdSsnNavigation")]
    public virtual ICollection<MultiChoiceResponse> MultiChoiceResponses { get; set; } = new List<MultiChoiceResponse>();

    [ForeignKey("Ssn")]
    [InverseProperty("Student")]
    public virtual User SsnNavigation { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<StudentExamModel> StudentExamModels { get; set; } = new List<StudentExamModel>();

    [InverseProperty("StudentSsnNavigation")]
    public virtual ICollection<StudentIntakeBranchDepartmentStudy> StudentIntakeBranchDepartmentStudies { get; set; } = new List<StudentIntakeBranchDepartmentStudy>();

    [InverseProperty("StdSsnNavigation")]
    public virtual ICollection<TrueFalseResponse> TrueFalseResponses { get; set; } = new List<TrueFalseResponse>();
}