// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class TeachAtResult
    {
        public int BId { get; set; }
        [StringLength(50)]
        public string BLoc { get; set; }
        public int DId { get; set; }
        [StringLength(10)]
        public string DName { get; set; }
        public int CId { get; set; }
        [StringLength(30)]
        public string CName { get; set; }
    }
}
