// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Core.Models
{
    public partial class TeachAtResult
    {
        public int BranchId { get; set; }
        [StringLength(50)]
        public string LGovernate { get; set; }
        [StringLength(6)]
        public string LZipCode { get; set; }
        public int DeptId { get; set; }
        [StringLength(10)]
        public string DeptName { get; set; }
        public int CourseId { get; set; }
        [StringLength(30)]
        public string CourseName { get; set; }
        public DateTime StartingDate { get; set; }
        public DateTime? EndingDate { get; set; }
    }
}
