// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[Table("test")]
public partial class Test
{
    [Key]
    [Column("QId")]
    public int Qid { get; set; }

    [Column("poolId")]
    public int? PoolId { get; set; }
}