// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[Index("Name", Name = "UQ__Topics__737584F6809249A7", IsUnique = true)]
public partial class Topic
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(30)]
    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Topic")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [ForeignKey("TopId")]
    [InverseProperty("Tops")]
    public virtual ICollection<Course> Crs { get; set; } = new List<Course>();
}