// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Core.Models;

[Index("Email", Name = "UniqueEmailConstriant", IsUnique = true)]
[Index("PhoneNumber", Name = "UniquePhoneConstriant", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("SSN")]
    public long Ssn { get; set; }

    [Required]
    [StringLength(50)]
    public string Fname { get; set; }

    [Required]
    [StringLength(50)]
    public string Lname { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(250)]
    public string PasswordHash { get; set; }

    [Required]
    [StringLength(6)]
    [Unicode(false)]
    public string ZipCode { get; set; }

    [Required]
    [StringLength(5)]
    [Unicode(false)]
    public string StreetNo { get; set; }

    [Column("BD")]
    public DateOnly Bd { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Gender { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string UserType { get; set; }

    public bool IsActive { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string ImageId { get; set; }

    [StringLength(250)]
    public string PasswordResetToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PasswordResetTokenExpiry { get; set; }

    [ForeignKey("ImageId")]
    [InverseProperty("Users")]
    public virtual ProfileImage Image { get; set; }

    [InverseProperty("SsnNavigation")]
    public virtual Staff Staff { get; set; }

    [InverseProperty("SsnNavigation")]
    public virtual Student Student { get; set; }

    [ForeignKey("ZipCode")]
    [InverseProperty("Users")]
    public virtual Location ZipCodeNavigation { get; set; }
}